version: "3.7"
services:
  postgres:
    image: td-postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      AIRFLOW_POSTGRES_USER: $AIRFLOW_POSTGRES_USER
      AIRFLOW_POSTGRES_PASSWORD: $AIRFLOW_POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  td-etl:
    image: td-etl
    build:
      context: ./etl
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: $ETL_HOST
      VIRTUAL_PORT: 8080
      LOAD_EX: n
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_USER: $AIRFLOW_POSTGRES_USER
      POSTGRES_PASSWORD: $AIRFLOW_POSTGRES_PASSWORD
      AIRFLOW__CORE__FERNET_KEY: $AIRFLOW_FERNET_KEY
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres://$AIRFLOW_POSTGRES_USER:$AIRFLOW_POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/airflow
      AIRFLOW_CONN_POSTGRES_ETL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$ETL_DB
      AIRFLOW_CONN_POSTGRES_PRISMA: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/prisma
    volumes:
      - ./etl/code/dags:/usr/local/airflow/dags
      - ./etl/code/data:/usr/local/airflow/data
      - ./etl/code/embulk:/usr/local/airflow/embulk
      - ./etl/code/sql:/usr/local/airflow/sql
      - ./etl/code/tests:/usr/local/airflow/tests
volumes:
  postgres:

networks:
  default:
    external:
      name: nginx-proxy
